version: "3"

services:
    nginx:
        image: clover/openresty
        ports:
            - 3500:3500
        volumes:
            - ./etc/nginx/conf.d/_.conf:/etc/nginx/conf.d/_.conf:ro
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - .:/www:ro
        restart: always
